### ISSUE TITLE
"ERROR: cannot import name 'MultiOutputMixin'" when adding text2img code into OWUI v0.4.7

### ISSUE THREAD

**Issue by Nordln** [pwillia7/open-webui-tools#1]
When adding the code from https://openwebui.com/t/lanolinoil/image_maker into v0.4.7, the code validates but fails on import with 
```ERROR: cannot import name 'MultiOutputMixin' from 'langchain_core.messages.tool' (/usr/local/lib/python3.11/site-packages/langchain_core/messages/tool.py)]"```

Running OWUI from the docker image ghcr.io/open-webui/open-webui:git-c4ea313 

Versions of requirements:
```
Name: requests
Version: 2.32.3
---
Name: langchain-openai
Version: 0.3.0
---
Name: langgraph
Version: 0.2.64
---
Name: ollama
Version: 0.4.6
---
Name: langchain-ollama
Version: 0.2.2
---
Name: websocket-client
Version: 1.8.0
```

**Comment by pwillia7** [comment]
Hi -- Do you get the same error using this version? 

https://github.com/pwillia7/open-webui-tools/blob/main/generate_image_tool.py

**Comment by Nordln** [comment]
Thanks for the reply. Yes this version does now load but I since upgraded to 0.5.7, so I cannot be sure the issue is fixed for 0.4.7.

**Comment by pwillia7** [comment]
Yes -- The way Open-Webui tools works changed in I believe 5.3 and the tool was updated. In case someone finds this in the future. The repo/commit below should work pre 5.3

https://github.com/pwillia7/open-webui-comfyui-imageprompt/tree/c436f241de8322ba3564473b5beb2e283661a243
